[package]
name = "shade-multi-test"
version = "0.1.0"
authors = [
   "hoomp <flammable.shower939@anonaddy.me>"
]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
airdrop = ["dep:airdrop"]

[dependencies]
airdrop = { path = "../../contracts/airdrop", optional = true }

shade-protocol = { path = "../shade_protocol", features = ["multi-test"] }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
shade-protocol = { path = "../shade_protocol", features = ["multi-test"] }
multi-derive = { path = "../multi_derive" }
